Test_Project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
   path('admin/', admin.site.urls),
   path('feed/', include('feed.urls', namespace='feed'))
]

feed/urls.py
# отвечает за парсинг url
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'feed'

urlpatterns = [
    path('', views.all_records, name='list_view'),
    path('<int:yy>/<int:mm>/<int:dd>/<slug:slug>',
         views.detailed_view,
         name='detailed_view'),
    path('<int:record_id>/send/', views.send_email, name='send_email'),
    path('create/', views.create_form, name='create_form'),

]

feed/models.py
from django.db import models

from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


# Create your models here.


class Record(models.Model):
    STATE = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    body = models.TextField('')
    state = models.CharField(max_length=10,
                             choices=STATE,
                             default='draft')

    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='all_records')

    slug = models.SlugField(max_length=250,
                            unique_for_date='pub')

    pub = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('feed:detailed_view',
                       args=[self.pub.year,
                             self.pub.month,
                             self.pub.day,
                             self.slug])

    def __str__(self):
        return self.title

feed/forms.py
from django import forms  # помогает делать джанго формы
from .models import Record


class SendEmailForm(forms.Form):   # форма отправки письма
    my_email = forms.CharField(max_length=100)
    address = forms.EmailField()
    comment = forms.CharField(required=False, widget=forms.Textarea)


class RecordForm(forms.ModelForm):

    class Meta:
        model = Record
        fields = ('title',
                  'body',
                  'state')

feed/views.py
from django.shortcuts import render, get_object_or_404
from feed.models import Record
from django.views.generic import ListView
from feed.forms import forms, SendEmailForm, RecordForm
from django.core.mail import send_mail

from django.contrib.auth.models import User


# Create your views here.
# экшен

def all_records(request):
    records = Record.objects.all()  # загрузка всего из базы
    return render(request, 'list.html', {'records': records})  # возрат в ответе


class RecordListView(ListView):  # получение всех записей
    queryset = Record.objects.all()
    context_object_name = 'records'
    template_name = 'list.html'  # шаблон базовый


def detailed_view(request, yy, mm, dd, slug):
    record = get_object_or_404(Record,
                               slug=slug,
                               pub__year=yy,
                               pub__month=mm,
                               pub__day=dd)
    return render(request,
                  'detailed.html',
                  {"record": record})


# обработчик формы для отправки письма

def send_email(request, record_id):
    obj = get_object_or_404(Record, id=record_id)
    sent = False
    if request.method == "POST":
        form = SendEmailForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            obj_url = request.build_absolute_uri(obj.get_absolute_url())
            subject = "Owner {} recommends you reading {}".format(cd['my_email'], obj.title)
            message = "Read {} at {} \n\nAdded comment: {}".format(obj.title,
                                                                   obj_url,
                                                                   cd['comment'])
            send_mail(subject, message, 'admin@myblog.com', [cd['address']])
            sent = True
    else:
        form = SendEmailForm()
    return render(request, 'send.html', {'record': obj,
                                         'form': form,
                                         'sent': sent})


def create_form(request):  # создание формы запроса
    if request.method == "POST":
        record_form = RecordForm(data=request.POST)
        if record_form.is_valid():
            new_record = record_form.save(commit=False)
            new_record.author = User.objects.first()   #получение любой первой записи из реляционной БД
            new_record.slug = new_record.title.replace(' ', '')  #избаввление слага от пробелов
            new_record.save()
            return render(request, 'detailed.html',
                          {'record': new_record})
        else:

            record_form = RecordForm()
            return render(request, 'createForm', {"form": record_form})

    record_form = RecordForm()
    return render(request, 'createForm.html', {'form': record_form})

feed/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script><![endif]-->
	 <title>{% block title %}{% endblock %} </title>
	<meta name="keywords" content="" />
	<meta name="description" content="" />
    <link href="{% static "styles.css"  %}" rel="stylesheet">
</head>

<body>

<div class="wrapper">

	<header class="header">
		<p>Here it would be a header</p>
    </header><!-- .header-->

	<div class="middle">

		<div class="container">
			<main class="content">
				{% block body %}{% endblock %}
            </main><!-- .content -->
		</div><!-- .container-->

		<aside class="left-sidebar">
			menu<br>
            menu<br>
        </aside><!-- .left-sidebar -->

	</div><!-- .middle-->

</div><!-- .wrapper -->

<footer class="footer">
    Maxim Belov for IT academy python dev course :) autumn 2019
</footer>

</body>
</html>

feed/templates/createForm.html
{% extends "base.html" %}
{% block title %}Create_new_record{% endblock %}
{% block body %}
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Create_new_record">
    </form>
{% endblock %}

feed/templates/detailed.html
{% extends "base.html" %}
{% block title %} {{record.title}} {% endblock %}

{% block body %}
<h1>{{record.title}}</h1>
<p>{{ record.body }}, Published by {{ record.author}}</p>
<a href="{% url "feed:send_email" record.id %}">Send_this_post</a>
{% endblock %}

feed/templates/detailed_view.html
{% extends "base.html" %}
{% block title %} {{record.title}} {% endblock %}

{% block body %}
<h1>{{record.title}}</h1>
<p>{{ record.body }}, Published by {{ record.author}}</p>
{% endblock %}

feed/templates/list.html
{% extends "base.html" %}
{% block title %}This is our block title{% endblock %}
{% block body %}
    {% for record in records %}
<h2> {{record.title}}</h2>
<p>published: {{record.pub}}, author = {{record.author}}</p>
<a href="{{ record.get_absolute_url }}">This is the link</a>
    {% endfor %}
{% endblock %}

feed/templates/send.html
{% extends "base.html" %}
{% block title %}Send link{% endblock %}
{% block body %}
{% if sent %}
    <h1> Email successfully send</h1>

{% else %}
    <h1>Share {{ record.title }} </h1>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Send e-mail">
    </form>
{% endif %}
{% endblock %}